M48
; DRILL file {KiCad 9.0.7} date 2026-04-02T17:20:40+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-02T17:20:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X3.475Y-3.475
X112.272Y-122.282
X150.0Y-57.0
X187.728Y-122.282
T2
X150.0Y-100.5
M30
